<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>API.Examples.SharedResources.OData</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.OData" Version="8.1.0" />
      <PackageReference Include="Asp.Versioning.OData.ApiExplorer" Version="8.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.2.5" />
      <PackageReference Include="Microsoft.OData.Core" Version="7.21.3" />
      <PackageReference Include="Microsoft.OData.Edm" Version="7.21.3" />
    </ItemGroup>

</Project>
